const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";

const routes = ["./routes.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "REST API - Manager Dev",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  tags: [],
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  paths: {
    "/": {
      get: {
        tags: [],
        description: "Endpoint para obter todas as tecnologias disponiveis",
        parameters: [],
        responses: {
          200: {
            description: "OK",
          },
        },
      },
    },
    "/developer/{id?}/{nome?}/{celular?}/{endereco?}/{especialidade?}": {
      get: {
        tags: ["developer"],
        description:
          "Endpoint para obter todos os dev's cadastrados, há possibilidade de filtrar atraves dos parametros opcionais",
        parameters: [],
        responses: {
          200: {
            description: "OK",
          },
        },
      },
    },
    "/developer": {
      post: {
        tags: ["developer"],
        description: "Endpoint para cadastrar um novo dev no banco",
        parameters: [],
        responses: {
          201: {
            description: "Successfully registered developer",
          },
        },
      },
    },
    "/developer/{id}": {
      put: {
        tags: ["developer"],
        description:
          "Endpoint para atualizar dados de um dev cadastrado usando como parametro de busca o id",
        parameters: ["id"],
        responses: {
          200: {
            description: "OK",
          },
        },
      },
      delete: {
        tags: [],
        description: "EndPoint para deletar um dev cadastrado no banco",
        parameters: ["id"],
        responses: {
          200: {
            description: "OK",
          },
        },
      },
    },
  },
};

swaggerAutogen(outputFile, routes, doc).then(() => {
  require("./index.js");
});
